name: Bug Report
description: File a bug report to help us improve
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees:
  - strataregula

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command: `lim scan --legacy-patterns "old_module"`
        2. With files containing: `import old_module`  
        3. Expected result: Should detect 1 import
        4. Actual result: No imports detected
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Ubuntu/Debian
        - CentOS/RHEL/Fedora
        - Other Linux
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of Python are you running?
      placeholder: "e.g. 3.11.5"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of legacy-import-migrator are you using?
      placeholder: "e.g. 0.1.0 (check with: pip show legacy-import-migrator)"
    validations:
      required: true

  - type: textarea
    id: command-output
    attributes:
      label: Command output
      description: Please paste the full command output (if applicable)
      render: shell
      placeholder: |
        $ lim scan --legacy-patterns "old_module" --verbose
        # Paste full output here

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Any other context about the problem here. You can attach images or files by clicking this area to highlight it and then dragging files in.
        
        Consider including:
        - Sample code files that reproduce the issue
        - Configuration files (pyproject.toml, etc.)
        - Full error tracebacks
        - Environment details (CI system, Docker, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true