blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/strataregula/legacy-import-migrator/blob/master/README.md
    about: Check the README for usage examples and troubleshooting
  - name: 💬 Discussions
    url: https://github.com/strataregula/legacy-import-migrator/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📊 PyPI Package
    url: https://pypi.org/project/legacy-import-migrator/
    about: View package details and installation instructions