name: Feature Request
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees:
  - strataregula

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🚀
        
        Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your specific use case for this feature.
      placeholder: |
        Example scenario:
        - I have a large codebase with 1000+ files
        - I need to migrate from `old_module` to `new_module`
        - Currently I have to manually check each file
        - This feature would allow me to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would be helpful"  
        - "Important for my workflow"
        - "Critical blocker"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "I've considered using X tool, but it doesn't work because..."

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas (optional)
      description: If you have ideas about how this could be implemented, please share!
      placeholder: |
        This could be implemented by:
        - Adding a new CLI option: --new-option
        - Extending the JSON output schema
        - etc.

  - type: dropdown
    id: contribution
    attributes:
      label: Would you be willing to contribute?
      description: Would you be interested in helping implement this feature?
      options:
        - "No, I can't contribute"
        - "Maybe, with guidance"
        - "Yes, I'd like to help"
        - "Yes, I can lead the implementation"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or examples about the feature request here.
        
        You can attach files by clicking this area to highlight it and then dragging files in.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true